---
language: ruby
cache: bundler
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
jobs:
  allow_failures:
  - rvm: ruby-head
addons:
  apt:
    packages:
    - auditd
    - libaudit-dev
install:
  - bundle install
before_script:
  - bundle exec rake clean
script:
  - bundle exec rake compile spec
